package kotlinf.practical_tasks

fun main() {
//    val firstType = FirstType()
//    firstType.task1()
//    firstType.task2()
//    firstType.task3()
//    firstType.task4()
//    firstType.task5()
//
    val secondType = SecondType()
//    secondType.task1()
//    secondType.task2()
//    secondType.task3()
//    secondType.task4()
//    secondType.task5()

//    val thirdType = ThirdType()
//    thirdType.task1()
//    thirdType.task2()
//    thirdType.task3()
//    thirdType.task4()
//    thirdType.task5()
//
//    val fourthType = FourthType()
//    val n = readlnOrNull()?.toIntOrNull() ?: return
//    var sum = fourthType.task1(n)
//    println(sum)
//    sum = fourthType.task2(n)
//    println(sum)
//    sum = fourthType.task3(n)
//    println(sum)
//    sum = fourthType.task4(n)
//    println(sum)
//    sum = fourthType.task5(n)
//    println(sum)
//
//    val fifthType = FifthType()
//    fifthType.task1()
//    fifthType.task2()
//    fifthType.task3()
//    fifthType.task4()
//    fifthType.task5()
//
//    val sixthType = SixthType()
//    sixthType.task1()
//    sixthType.task2()
//    sixthType.task3()
//    sixthType.task4()
//    sixthType.task5()
//
//    val seventhType = SeventhType()
//    seventhType.task1()
//    seventhType.task2()
//    seventhType.task3()
//    seventhType.task4()
//    seventhType.task5()
//
//    val eighthType = EighthType()
//    eighthType.task1()
//    eighthType.task2()
//    eighthType.task3()
//    eighthType.task4()
//    eighthType.task5()
//
//    val ninthType = NinthType()
//    ninthType.task1()
//    println("\n")
//    ninthType.task2()
//    println("\n")
//    ninthType.task3()
//    println("\n")
//    ninthType.task4()
//    println("\n")
//    ninthType.task5()
//
//    val tenthType = TenthType()
//    tenthType.task1()
//    tenthType.task2()
//    tenthType.task3()
//    tenthType.task4()
//    tenthType.task5()
//
//    val eleventhType = EleventhType()
//    eleventhType.singleResponsibilityPrinciple(5)
//    eleventhType.openClosedPrinciple(5)
//    eleventhType.dependencyInversionPrinciple(5)
//
//    val twelfthType = TwelfthType<String>()
//    twelfthType.add("qwerty")
//    twelfthType.add("fred")
//    twelfthType.add("alex")
//    twelfthType.add("asp.net")
//    twelfthType.add("john")
//    twelfthType.printList()
//    twelfthType.delete("qwerty")
//    twelfthType.delete("john")
//    println()
//    twelfthType.printList()
}